DROP TABLE IF EXISTS customer CASCADE;

DROP TABLE IF EXISTS customer_update_history CASCADE;

CREATE TABLE customer(
 id bigint generated by default as identity,
 status varchar(190) not null,
 first_name varchar(190),
 last_name varchar(190),
 email varchar(190),
 phone_number varchar(190) not null,
 created_at timestamp not null,
 last_updated_at timestamp not null,
 PRIMARY KEY  (id)
);

CREATE TABLE customer_update_history(
 id bigint generated by default as identity,
 customer_id bigint not null,
 status varchar(190) not null,
 first_name varchar(190),
 last_name varchar(190),
 email varchar(190),
 phone_number varchar(190) not null,
 creator_id bigint not null,
 created_at timestamp not null,
 PRIMARY KEY  (id)
);

CREATE UNIQUE INDEX customer_phone_number_status_uk ON customer(phone_number, status);
